services:
  - type: web
    name: ecocash-wealth
    env: docker
    repo: https://github.com/eveline3569/EcoInvestPro
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /